import { describe, expect, it } from 'vitest';

import { downscaleImageFile } from '$lib/place-media/downscale-image';

// Real-browser coverage (place-media review fix) for the two canvas behaviours that pure dimension
// math in tests/unit/place-media/downscale-image.test.ts cannot exercise: EXIF re-orientation and
// transparency flattening both require an actual createImageBitmap/<canvas> pipeline.

// Builds a solid-color canvas and returns it as a Blob encoded with the given MIME type. Every
// fixture in this file is generated by the browser itself rather than committed as a binary file.
async function buildCanvasBlob(
  width: number,
  height: number,
  type: 'image/jpeg' | 'image/png',
  paint: (context: CanvasRenderingContext2D) => void
): Promise<Blob> {
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const context = canvas.getContext('2d');
  if (!context) {
    throw new Error('Canvas 2D context is unavailable');
  }
  paint(context);

  const blob = await new Promise<Blob | null>((resolve) => {
    canvas.toBlob(resolve, type, 0.92);
  });
  if (!blob) {
    throw new Error('Canvas could not encode the fixture image');
  }
  return blob;
}

// Splices a minimal Exif APP1 segment carrying a single Orientation tag right after the JPEG SOI
// marker (0xFFD8). Browser-encoded canvas JPEGs carry no Exif of their own, so this is the only
// way to produce an oriented fixture without a real camera file or an image library dependency.
// The segment layout: "Exif\0\0" + a little-endian TIFF header (IFD0 offset 8) + a one-entry IFD0
// (tag 0x0112 Orientation, type SHORT, count 1, the orientation value) + a zero "no next IFD".
function spliceExifOrientation(
  jpegBytes: Uint8Array<ArrayBuffer>,
  orientation: number
): Uint8Array<ArrayBuffer> {
  const exifData = new Uint8Array([
    0x45,
    0x78,
    0x69,
    0x66,
    0x00,
    0x00, // "Exif\0\0"
    0x49,
    0x49,
    0x2a,
    0x00, // TIFF header: little-endian, magic 42
    0x08,
    0x00,
    0x00,
    0x00, // offset to IFD0
    0x01,
    0x00, // IFD0 entry count: 1
    0x12,
    0x01, // tag 0x0112 (Orientation)
    0x03,
    0x00, // type 3 (SHORT)
    0x01,
    0x00,
    0x00,
    0x00, // count 1
    orientation & 0xff,
    (orientation >> 8) & 0xff,
    0x00,
    0x00, // value, zero-padded to 4 bytes
    0x00,
    0x00,
    0x00,
    0x00 // next IFD offset: none
  ]);

  const segmentLength = exifData.length + 2; // includes the 2-byte length field itself
  const app1 = new Uint8Array(2 + segmentLength);
  app1[0] = 0xff;
  app1[1] = 0xe1;
  app1[2] = (segmentLength >> 8) & 0xff;
  app1[3] = segmentLength & 0xff;
  app1.set(exifData, 4);

  const soi = jpegBytes.slice(0, 2);
  const rest = jpegBytes.slice(2);
  const spliced = new Uint8Array(soi.length + app1.length + rest.length);
  spliced.set(soi, 0);
  spliced.set(app1, soi.length);
  spliced.set(rest, soi.length + app1.length);
  return spliced;
}

async function readPixel(
  file: File,
  x: number,
  y: number
): Promise<{ r: number; g: number; b: number; a: number }> {
  const bitmap = await createImageBitmap(file);
  try {
    const canvas = document.createElement('canvas');
    canvas.width = bitmap.width;
    canvas.height = bitmap.height;
    const context = canvas.getContext('2d');
    if (!context) {
      throw new Error('Canvas 2D context is unavailable');
    }
    context.drawImage(bitmap, 0, 0);
    const [r, g, b, a] = context.getImageData(x, y, 1, 1).data;
    return { r: r ?? 0, g: g ?? 0, b: b ?? 0, a: a ?? 0 };
  } finally {
    bitmap.close();
  }
}

describe('downscaleImageFile (real browser canvas)', () => {
  it('uses the non-blocking OffscreenCanvas encoder when it is available', async () => {
    expect(typeof OffscreenCanvas).toBe('function');
    const blob = await buildCanvasBlob(40, 30, 'image/png', (context) => {
      context.fillStyle = '#2a6b4a';
      context.fillRect(0, 0, 40, 30);
    });
    const file = new File([blob], 'offscreen.png', { type: 'image/png' });
    const originalToBlob = HTMLCanvasElement.prototype.toBlob;
    HTMLCanvasElement.prototype.toBlob = () => {
      throw new Error('The DOM canvas encoder should not be used when OffscreenCanvas is ready');
    };

    try {
      const result = await downscaleImageFile(file, 1600, 0.85);
      expect(result.file.type).toBe('image/jpeg');
      expect(result.width).toBe(40);
      expect(result.height).toBe(30);
    } finally {
      HTMLCanvasElement.prototype.toBlob = originalToBlob;
    }
  });

  it('re-orients a portrait EXIF photo so the stored dimensions are display-oriented', async () => {
    // The sensor capture is landscape (120x80); Orientation 6 means "rotate 90 degrees clockwise
    // to display correctly", so a correctly-oriented read must report portrait 80x120 - the
    // dimensions a phone camera would actually report for a portrait shot.
    const sensorWidth = 120;
    const sensorHeight = 80;
    const blob = await buildCanvasBlob(sensorWidth, sensorHeight, 'image/jpeg', (context) => {
      context.fillStyle = '#2a6b4a';
      context.fillRect(0, 0, sensorWidth, sensorHeight);
    });
    const orientedBytes = spliceExifOrientation(new Uint8Array(await blob.arrayBuffer()), 6);
    const file = new File([orientedBytes], 'portrait.jpg', { type: 'image/jpeg' });

    const result = await downscaleImageFile(file, 1600, 0.85);

    expect(result.width).toBe(sensorHeight);
    expect(result.height).toBe(sensorWidth);
  });

  it('fills transparent pixels white instead of flattening them to black on JPEG re-encode', async () => {
    const width = 20;
    const height = 20;
    // The canvas starts fully transparent; drawing nothing leaves every pixel alpha = 0.
    const blob = await buildCanvasBlob(width, height, 'image/png', () => {});
    const file = new File([blob], 'transparent.png', { type: 'image/png' });

    const result = await downscaleImageFile(file, 1600, 0.85);
    expect(result.file.type).toBe('image/jpeg');

    const pixel = await readPixel(result.file, 5, 5);
    expect(pixel.r).toBeGreaterThan(250);
    expect(pixel.g).toBeGreaterThan(250);
    expect(pixel.b).toBeGreaterThan(250);
  });
});
